### ISSUE TITLE
docker: sirfuser does not have permissions for /devel directory

### ISSUE THREAD

**Issue by paskino** [SyneRBI/SIRF-SuperBuild#536] opened 2021-05-12 20:34 UTC
On a locally built image `sirfuser `does not have permissions for /devel directory, as a consequence `SIRF-Exercises` do not get installed.

Interestingly this does not seem to happen for travis built images.

**Comment by KrisThielemans** [comment] 2021-05-12 20:38
sorry. duplicate of #464 with explanation why

**Closed by KrisThielemans** 2021-05-12 20:38 UTC
