### ISSUE TITLE
Jupyter terminal prompt

### ISSUE THREAD

**Issue by DANAJK** [SyneRBI/SIRF-SuperBuild#468] opened 2021-01-12 10:19 UTC
This may just be my odd set-up (Ubuntu VM, needing sudo to allow Docker to provide a Jupyter window in Firefox), but when I open a terminal in Jupyter, the command prompt is not properly set resulting in the following error message frequently:
`/bin/sh: 1: __git_ps1: not found`
`(base) sirf:\w$`

**Comment by KrisThielemans** [comment] 2021-05-20 20:41
Duplicate of #540

**Closed by KrisThielemans** 2021-05-20 20:41 UTC
