### ISSUE TITLE
disable docker builds for PRs or even branches

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#332] opened 2020-02-24 13:34 UTC
there seems little value in running the docker builds for most PRs. @rijobro says that they are still failing for PRs from forks anyway.

What about enabling docker builds only for commits to `master`? Seems easy enough: https://docs.travis-ci.com/user/conditional-builds-stages-jobs

**Comment by KrisThielemans** [comment] 2020-02-24 13:34
@casperdcl any objections?

**Comment by casperdcl** [comment] 2020-02-24 14:15
Is this a duplicate of #331? Just want to make sure it's the same issue first...

**Comment by rijobro** [comment] 2020-02-24 14:18
> Is this a duplicate of #331? Just want to make sure it's the same issue first...

yes

**Comment by KrisThielemans** [comment] 2020-03-19 11:11
Relevant here is https://github.com/CCPPETMR/SIRF-SuperBuild/pull/361#issuecomment-601102294

**Comment by casperdcl** [comment] 2020-03-19 12:58
Ping myself

**Closed** 2020-05-22 11:50 UTC
Labels: bug
