### ISSUE TITLE
GHA: docker always builds master

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#775] opened 2022-11-11 22:20 UTC
https://github.com/SyneRBI/SIRF-SuperBuild/blob/a0ad95c056cd7f666d8e09f296d1234227d50bef/docker/Dockerfile#L127-L128
and https://github.com/SyneRBI/SIRF-SuperBuild/blob/a0ad95c056cd7f666d8e09f296d1234227d50bef/docker/user_sirf-ubuntu.sh#L11-L13
But this means that running the docker actions on GHA doesn't make sense for most PRs (unless it actually modifies docker files). We could disable the action on these PRs I guess (with some clever tricks to make sure modifications to the `docker/*`).

At present, we're wasting a lot of computation time...

**Comment by paskino** [comment] 2022-11-15 07:53
This is linked or possibly a duplicate of #664 and #597

**Comment by paskino** [comment] 2023-08-10 08:37
@casperdcl I tried to copy the SuperBuild files from the local directory to the container. It works with the caveat that once you touch any file it rebuilds the image from the initial point! I haven't investigated any solutions to this.

**Closed** 2024-02-21 22:37 UTC
